# ------------------------------------------------------------
# In this file, you can make some modifications to the Streamlit
# app's global environment. 
#
# All of the possible config options can be found here:
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# ------------------------------------------------------------


[client]
# Turning the default sidebar navigation off so we 
# can use our own
showSidebarNavigation = false

[theme]
# Setting some basic config options related to the theme of the app
base = "light"
backgroundColor = "#f0f4fb"               # Soft pastel blue/gray (clean + modern)
primaryColor = "#365fc7"                  # Classy blue for buttons
secondaryBackgroundColor = "#a5c6f2"      # Rich navy for sidebar
textColor = "#1b1c1e"                     # Dark charcoal text (not harsh black)
font = "sans serif"
