USE loyalty_lines;

-- PREPARE POLIICAL PARTIES
INSERT INTO political_party (partyName, partyDescription)
VALUES ("Group of the European People's Party", "The EPP is the largest political group and represents center-right, Christian democratic, and pro-European values. It supports a strong EU, market economy, and conservative social policies.");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("Group of the Progressive Alliance of Socialists and Democrats in the European Parliament");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("Patriots for Europe Group");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("European Conservatives and Reformists Group");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("Renew Europe Group");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("Group of the Greens/European Free Alliance");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("The Left group in the European Parliament");

INSERT INTO political_party (partyName, partyDescription)
VALUES ("Europe of Sovereign Nations Group");

-- PREPARE USER ROLES
INSERT INTO userRole(userRoleID, userRoleName)
VALUES (1, "PartyLeader");

INSERT INTO userRole(userRoleID, userRoleName)
VALUES (2, "PoliticalJournalist");

INSERT INTO userRole(userRoleID, userRoleName)
VALUES (3, "Citizen");

-- PREARE USER PERSONAS
INSERT INTO user (age, countryOfOrigin, firstName, lastName, partyID, userRoleID)
VALUES ("59", "Greece", "Yanni", "Polous", 1, 3);

INSERT INTO user (age, countryOfOrigin, firstName, lastName, userRoleID)
VALUES ("30", "Spain", "Camila", "Romero", 2);

INSERT INTO user (age, countryOfOrigin, firstName, lastName, partyID, userRoleID)
VALUES ("23", "Switzerland", "Greg", "Gerborg", 3, 1);

-- INSERT MOCK MEPs
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (1,'Waring Nyland','Thailand',22,6,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (2,'Nissy Drakard','China',85,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (3,'Consolata Baudone','Japan',41,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (4,'Mordecai Dilks','Indonesia',61,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (5,'Jamal Kinnin','Norway',98,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (6,'Hulda Colville','Canada',14,1,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (7,'Kirstyn Gowen','Portugal',47,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (8,'Adler Dumingos','Portugal',92,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (9,'Lenee Spir','China',15,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (10,'Rudyard O''Cridigan','Sweden',12,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (11,'Tarrah Scatchard','Poland',2,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (12,'Uta Squirrel','Philippines',85,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (13,'Felipe Newick','China',1,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (14,'Dorian Rickardes','China',26,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (15,'Francis Berston','Portugal',14,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (16,'Nalani Dommerque','Norway',91,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (17,'Wilone Larvor','China',78,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (18,'Bartholomeo Backshell','Dominican Republic',83,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (19,'Tobin Mallalieu','Russia',95,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (20,'Hurlee Meaders','Brazil',90,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (21,'Fiona Knight','Vietnam',76,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (22,'Jacinta McLaren','Uzbekistan',82,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (23,'Billye Bletso','Brazil',16,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (24,'Marni Rodden','Brazil',74,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (25,'Olia Yoxall','Poland',57,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (26,'Elora Wigan','United States',77,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (27,'Freedman Sorbie','Indonesia',3,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (28,'Elsy Wennington','China',72,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (29,'Quinn Pulford','China',67,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (30,'Clifford Wake','Argentina',91,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (31,'Marie-jeanne Maffucci','China',41,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (32,'Timi Bartelet','United States',3,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (33,'Tory Santon','France',84,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (34,'Ammamaria Breed','China',45,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (35,'Zitella Luipold','Spain',72,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (36,'Hazel Ruddell','China',23,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (37,'Gaspard Westmancoat','Sweden',8,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (38,'Hedvig Conor','Sweden',62,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (39,'Erastus Denver','Indonesia',1,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (40,'Clayborne Hollidge','Croatia',75,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (41,'Leese Hollow','Poland',50,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (42,'Jaimie Worledge','New Zealand',31,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (43,'Sheri Lindeboom','Philippines',76,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (44,'Tasia Raper','Russia',26,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (45,'Karee Ellor','Honduras',52,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (46,'Stearn Imlaw','Ukraine',17,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (47,'Janice Chatain','Portugal',79,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (48,'Agnella Valencia','Russia',73,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (49,'Fonsie Pampling','Indonesia',43,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (50,'Lonnie Maskall','Madagascar',34,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (51,'Jobyna Montague','Philippines',20,1,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (52,'Mariquilla Hatton','Costa Rica',20,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (53,'Bunnie Bayford','Equatorial Guinea',22,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (54,'Rob Wildor','China',56,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (55,'Janine Mainland','Brazil',22,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (56,'Justus Sline','China',89,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (57,'Anestassia Shillam','Russia',90,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (58,'Blakeley Waleran','Portugal',20,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (59,'Caroline Gianinotti','Kazakhstan',76,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (60,'Kristan Francais','Russia',18,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (61,'Stefania Fairest','Cuba',66,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (62,'Dacy Harvie','Russia',51,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (63,'Lazaro Behninck','Brazil',90,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (64,'Debera Zwicker','Ireland',8,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (65,'Redd Pryor','China',44,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (66,'Chrysler Shekle','Serbia',57,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (67,'Dyana Simonard','Lebanon',70,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (68,'Leeland Reynish','Portugal',64,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (69,'Chevalier Tunna','Sweden',19,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (70,'Rikki Petegree','China',46,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (71,'Redd Lehrle','Papua New Guinea',90,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (72,'Ellie Roman','China',74,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (73,'Bird Dunton','Jordan',0,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (74,'Russ Shitliffe','France',41,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (75,'Paige Lemery','China',61,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (76,'Bekki Scohier','Indonesia',65,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (77,'Erich Keady','Vietnam',33,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (78,'Krishnah Wager','Vietnam',39,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (79,'Lizette Mauchlen','Malawi',95,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (80,'Davide Eaken','Ukraine',14,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (81,'Chandler Molloy','Colombia',16,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (82,'Henri Lambricht','China',24,6,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (83,'Melisande Tembey','Finland',70,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (84,'Hamnet Le feaver','Philippines',7,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (85,'Lek Rixon','Kazakhstan',46,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (86,'Rozina Hacksby','China',37,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (87,'Cy Meagh','Peru',95,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (88,'Sigismund Tink','Guatemala',7,6,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (89,'Theobald Bellerby','Poland',11,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (90,'Melosa Crispe','China',51,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (91,'Gerhard Banbury','Luxembourg',76,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (92,'Adler Wellen','Portugal',89,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (93,'Shurwood Torri','Iran',41,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (94,'Molli Blachford','Indonesia',53,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (95,'Caresse Jennrich','France',94,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (96,'Bat Rabb','Sweden',100,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (97,'Torrin Sperry','China',45,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (98,'Silvia Endrizzi','Philippines',58,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (99,'Cleveland Cabedo','Germany',82,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (100,'Katie Tireman','Peru',44,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (101,'Ceil Langmead','Tanzania',44,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (102,'Dedra Faire','Israel',15,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (103,'Debera Gwyllt','Sweden',10,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (104,'Jeannine Lindner','Indonesia',40,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (105,'Nance Hryncewicz','Burundi',54,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (106,'Yetta Hrinchishin','Russia',63,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (107,'Corbie MacDermot','China',56,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (108,'Sella Murie','Indonesia',73,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (109,'Bronny Kittless','Colombia',36,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (110,'Edita Chazerand','Afghanistan',86,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (111,'Tressa Tennick','Russia',64,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (112,'Camille Haydon','Mexico',44,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (113,'Laverna Flores','China',24,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (114,'Lindsay Betun','Netherlands',31,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (115,'Lilith Overell','Portugal',20,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (116,'Heddi Smerdon','Brazil',61,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (117,'Jessie Genty','China',65,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (118,'Jae Gossling','Portugal',45,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (119,'Gifford Iceton','Serbia',47,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (120,'Simone Davern','Philippines',33,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (121,'Genna Lorden','Indonesia',99,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (122,'Juli Keri','Ireland',70,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (123,'Jeannine Keepin','Canada',27,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (124,'Buckie Lanham','Ukraine',24,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (125,'Carleen Mathwen','Indonesia',79,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (126,'Boyd Tryhorn','Philippines',51,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (127,'Lydia Kenworthy','Croatia',25,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (128,'Francisca Ortelt','Russia',13,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (129,'Aarika Tumelty','Indonesia',44,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (130,'Bartholomeus Axon','China',20,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (131,'Mufinella Briddock','Canada',99,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (132,'Carla Hehl','Jordan',9,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (133,'Roanne Hallett','Indonesia',26,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (134,'Arielle Waddingham','Estonia',37,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (135,'Weston Try','China',7,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (136,'Vassili Tolputt','Brazil',66,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (137,'Harriott Searson','France',92,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (138,'Sophronia Taveriner','Indonesia',62,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (139,'Gisela Brose','China',93,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (140,'Jean Ferens','Indonesia',7,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (141,'Sigismund Parffrey','Portugal',0,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (142,'Armand Gilluley','China',52,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (143,'Eddi Bulfield','Peru',53,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (144,'Trumann Ruben','Croatia',69,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (145,'Ida MacCarrane','Greece',74,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (146,'Allianora Ambrozewicz','Philippines',88,1,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (147,'Gabriella Shenton','China',70,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (148,'Aliza Morando','China',26,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (149,'Siana Merman','Indonesia',84,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (150,'Cherrita Gurry','China',18,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (151,'Lurline Bowers','Philippines',18,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (152,'Hamlin Oleshunin','Japan',18,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (153,'Ed Cram','Portugal',56,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (154,'Magnum Mochan','Philippines',91,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (155,'Edie Markie','Croatia',45,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (156,'Dal Cracknell','Philippines',0,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (157,'Lukas Allin','Philippines',46,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (158,'Loise Laverock','China',66,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (159,'Flo Russen','Portugal',47,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (160,'Berton Stoppard','Jamaica',82,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (161,'Winifred Flescher','China',29,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (162,'Hynda MacInnes','Indonesia',37,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (163,'Allys Baitey','Greece',37,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (164,'Annamaria Pawling','Mongolia',83,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (165,'Sileas Thorouggood','Portugal',22,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (166,'Jinny Heinle','Russia',80,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (167,'Rebecca Shinner','Uganda',66,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (168,'Arty Elcoux','France',22,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (169,'Nevins Petley','Uganda',70,6,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (170,'Merrili Hakking','Indonesia',95,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (171,'Lilith Lowthorpe','Portugal',6,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (172,'Hedy Bonhomme','China',39,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (173,'Rheta Hilbourne','China',64,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (174,'Wanda Klemz','Cyprus',35,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (175,'Reina Izkovicz','Ivory Coast',49,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (176,'Nertie Jackling','South Korea',34,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (177,'Whitaker Stonary','China',66,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (178,'Clayson Meiner','China',8,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (179,'Lowe Renny','Indonesia',27,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (180,'Virginia Thatcher','United States',4,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (181,'Sadie Klemps','Mexico',90,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (182,'Randall Moncrieffe','China',99,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (183,'Kali Avrahamoff','Chile',17,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (184,'Christa Figgins','Ukraine',34,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (185,'Hulda Blockwell','China',95,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (186,'Hazlett Ascroft','Sweden',97,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (187,'Edgardo Feaster','Iran',64,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (188,'Teddie Addington','Indonesia',54,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (189,'Tabitha Stathers','Albania',30,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (190,'Edward Mc Comb','Colombia',41,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (191,'Roxanne Dickens','France',97,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (192,'Moise Pomeroy','China',75,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (193,'Drusi Tassell','Philippines',53,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (194,'Charin Bryde','Indonesia',6,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (195,'Asia Willgoose','Sri Lanka',70,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (196,'Clive Loveguard','Lesotho',75,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (197,'Arther Tremberth','Indonesia',25,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (198,'Dall Benedyktowicz','Tunisia',30,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (199,'Suzanne Gutteridge','China',93,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (200,'Ardelia Dugald','Japan',19,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (201,'Godfree Roelvink','Malawi',1,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (202,'Lyle Frensch','Portugal',61,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (203,'Nissie Crowche','Russia',56,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (204,'Clio Kitteridge','Portugal',41,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (205,'Birdie Siggers','Ukraine',51,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (206,'Gabriele Pinnington','United States',8,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (207,'Malinde Blaksland','Japan',78,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (208,'Jeannine Elderbrant','China',67,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (209,'Cherlyn Culmer','China',86,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (210,'Sileas Fairnie','Indonesia',94,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (211,'L;urette Vallantine','Sweden',61,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (212,'Sarge Frudd','France',1,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (213,'Cindee McKeighan','Brazil',0,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (214,'Evangelia Tyre','China',65,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (215,'Adriane Toomer','China',7,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (216,'Emilia Pfeuffer','Peru',12,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (217,'Emelita Skeemor','Uzbekistan',14,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (218,'Ulysses Findley','Indonesia',25,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (219,'Ahmed Capon','Croatia',28,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (220,'Berky Took','Colombia',31,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (221,'Simonette Hedylstone','Russia',65,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (222,'Elicia Sibson','France',72,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (223,'Trey Sherwell','Russia',64,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (224,'Jody Dowtry','Poland',10,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (225,'Hazel Shury','Peru',80,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (226,'Romonda Lazenbury','Indonesia',5,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (227,'Annnora Inchley','Argentina',89,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (228,'Bamby Voak','United States',88,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (229,'Vincents Davidow','Marshall Islands',31,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (230,'Kessiah Waltering','Indonesia',9,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (231,'Brenn Musselwhite','North Korea',5,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (232,'Priscella Voysey','Sweden',47,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (233,'Isobel Immins','Uruguay',11,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (234,'Chrisse Baszniak','United States',96,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (235,'Packston Coghlan','Brazil',65,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (236,'Wendi Murr','Brazil',99,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (237,'Ursala Travis','China',42,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (238,'Lyn Escott','Indonesia',36,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (239,'Garnette Mesant','Portugal',6,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (240,'Brigham Housby','Ukraine',39,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (241,'Rivy Spyby','Costa Rica',50,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (242,'Coretta Norcross','Mali',92,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (243,'Ericha Bischof','China',27,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (244,'Edi Casement','Sweden',8,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (245,'Agosto Fargher','United States',2,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (246,'Masha Rotham','China',8,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (247,'Doralyn Dring','France',74,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (248,'Dode Braund','Russia',43,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (249,'Desiri MacGiolla','Ukraine',83,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (250,'Cloe Spafford','Indonesia',81,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (251,'Rochell Willwood','Panama',11,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (252,'Sebastien Pickersgill','France',63,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (253,'Morgun Asser','Slovenia',24,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (254,'Nessy Markus','China',8,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (255,'Miltie Rizzardini','Russia',40,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (256,'Ludovika Lockley','Germany',72,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (257,'Tomkin Stoneman','Philippines',41,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (258,'Chrisse Clews','China',97,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (259,'Fidel Easthope','Peru',59,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (260,'Carmelina Bellow','Indonesia',18,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (261,'Bond Conner','Syria',26,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (262,'Scotty Chazotte','Philippines',31,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (263,'Adriana Render','Philippines',13,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (264,'Felice Durtnall','Republic of the Congo',16,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (265,'Celestina Astbery','United States',44,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (266,'Blancha Fryett','Chile',62,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (267,'Diannne Carek','Indonesia',81,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (268,'Natalya Stenett','Ukraine',93,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (269,'Randolf Sorby','United States',46,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (270,'Antoinette Harwood','Tanzania',44,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (271,'Elianore Bimrose','El Salvador',73,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (272,'Alvinia Benedick','Poland',9,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (273,'Giovanni Schulz','Czech Republic',83,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (274,'Tommi Stratten','Portugal',68,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (275,'Ofelia Moscrop','Philippines',48,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (276,'Alfredo Pavitt','Philippines',72,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (277,'Myca Zuker','Philippines',72,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (278,'Nadia Kilbey','Russia',98,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (279,'Renate Gaucher','United States',19,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (280,'West Scoffins','Indonesia',47,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (281,'Dougie Kerr','Vietnam',73,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (282,'Garner Aucock','Mexico',45,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (283,'Yves O''Kerin','Brazil',2,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (284,'Philis Newe','Indonesia',42,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (285,'Rosalynd Libbey','Brazil',53,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (286,'Lemmy Lloyd-Williams','Philippines',90,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (287,'Zachary Falconar','China',12,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (288,'Miltie Pipes','Germany',20,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (289,'Kendrick Rawls','Germany',67,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (290,'Sanders Guenther','France',22,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (291,'Reilly Brettel','Cuba',54,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (292,'Goldia Younger','China',20,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (293,'Garvy Ratlee','China',20,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (294,'Kizzie Bartot','Brazil',89,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (295,'Renelle Cattemull','China',61,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (296,'Lib Sharplin','Indonesia',75,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (297,'Beverly Schindler','Armenia',69,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (298,'Law Brogden','Indonesia',55,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (299,'Millicent Paiton','New Zealand',81,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (300,'Daryn Cudd','Indonesia',35,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (301,'Granny McClary','Haiti',14,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (302,'Harri Tatum','Ukraine',6,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (303,'Correna Filipowicz','Japan',80,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (304,'Jordan Haslin','Kazakhstan',57,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (305,'Cathryn Mattisson','Indonesia',20,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (306,'Cairistiona Coldicott','Colombia',69,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (307,'Charline Spraggon','Brazil',88,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (308,'Alexandre McGonagle','Russia',60,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (309,'Sophey Casaroli','Croatia',79,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (310,'Eba Eefting','Philippines',19,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (311,'Dolorita Shenfish','Cuba',83,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (312,'Franzen Antoniazzi','Russia',97,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (313,'Billye Rankine','Nigeria',42,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (314,'Kingston Toope','Poland',1,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (315,'Torie Hammell','Russia',87,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (316,'Yorgo Manhood','Syria',21,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (317,'Bradly Kemsley','Portugal',26,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (318,'Chad Elleyne','Brazil',72,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (319,'Sukey Carmel','Belarus',76,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (320,'Gussy Sellman','Philippines',69,6,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (321,'Harland Dobrowolski','China',19,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (322,'Shem Lilleman','Honduras',0,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (323,'Elena Luff','China',75,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (324,'Andonis Karppi','Costa Rica',60,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (325,'Sansone Capron','Canada',35,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (326,'Nealson Malling','Canada',90,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (327,'Weston Joynes','China',0,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (328,'Netti Croisier','Poland',69,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (329,'Odella Bromwich','China',56,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (330,'Bekki Winder','Sweden',74,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (331,'Carine Romi','Ukraine',1,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (332,'Ruben Eisikovitsh','Serbia',62,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (333,'Cherilyn Beggini','United States',71,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (334,'Vanna Cornewall','France',81,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (335,'Gunar Cobain','Peru',13,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (336,'Kaitlyn Wittleton','Vietnam',65,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (337,'Viviana Cassells','China',43,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (338,'Ardis Feldmark','Canada',28,6,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (339,'Vikky Bloy','Myanmar',96,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (340,'Bethany Salatino','Pakistan',55,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (341,'Felice Safe','United States',91,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (342,'Morrie Lamkin','Afghanistan',74,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (343,'Ezri Marsh','Honduras',35,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (344,'Burtie Paige','Thailand',40,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (345,'Marje Lascelles','Czech Republic',74,1,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (346,'Antoinette Steanyng','China',58,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (347,'Sutton Wyley','China',70,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (348,'Cammi Tuxwell','China',81,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (349,'Marge Rudd','Venezuela',34,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (350,'Sofie Raye','Bulgaria',77,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (351,'Roshelle Grubey','Portugal',16,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (352,'Benito Squirrel','France',92,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (353,'Cati Gerasch','Israel',39,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (354,'Torry O''Connolly','Indonesia',57,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (355,'Sara-ann Hammerberger','China',3,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (356,'Chrisse Birkmyre','Indonesia',3,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (357,'Audie McMurtyr','Russia',81,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (358,'Kristal Escot','China',38,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (359,'Tracee Criple','Indonesia',81,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (360,'Jaine Vlasenko','Zambia',68,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (361,'Richart Vanes','Cameroon',10,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (362,'Floris Himsworth','Indonesia',49,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (363,'Ansel Hansana','Poland',14,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (364,'Kayle Sharvell','France',30,6,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (365,'Miltie Stretton','China',67,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (366,'Corbie Boyer','Ivory Coast',62,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (367,'Carol-jean Enga','Russia',18,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (368,'Boniface Borrell','Mexico',61,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (369,'Trev Chave','Thailand',72,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (370,'Darrel Odom','Finland',21,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (371,'Aurore Pearman','Finland',51,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (372,'Cordelia Blasli','Argentina',16,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (373,'Griffie Hollyland','Norway',4,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (374,'Leonhard Amps','Peru',80,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (375,'Porty Bottini','Indonesia',66,6,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (376,'Aurora Lotwich','China',85,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (377,'Wenona Orrill','Tajikistan',83,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (378,'Glenden Tippell','Greece',55,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (379,'Cornall Yegorov','China',56,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (380,'Crawford Borgesio','Ireland',67,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (381,'Nahum McCaughey','China',4,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (382,'Hartley Victor','Nigeria',83,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (383,'Tobiah Lampke','Armenia',8,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (384,'Friedrich Shallow','Macedonia',24,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (385,'Eduardo Bloschke','Indonesia',6,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (386,'Loren Esberger','Sweden',55,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (387,'Maxwell Iglesia','Russia',23,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (388,'Hattie Spire','Honduras',96,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (389,'Kenna Scotchmur','Greece',1,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (390,'Sargent Wressell','China',33,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (391,'Fredi Picken','Niger',47,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (392,'Sharity Patters','Japan',49,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (393,'Dev Tows','China',45,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (394,'Elisha Aldwich','Indonesia',34,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (395,'Latashia Heephy','Nigeria',2,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (396,'Sidnee Whisker','Brazil',70,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (397,'Carly Ennor','Russia',18,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (398,'Rosemaria Lys','Madagascar',29,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (399,'Brodie Cluitt','Sri Lanka',66,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (400,'Roseann Benet','Croatia',74,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (401,'Luci Garthshore','Thailand',34,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (402,'Lorene Jendrys','China',90,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (403,'Kyla Luciani','France',36,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (404,'Tallie Niesegen','China',32,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (405,'Thorsten Kerfut','Ukraine',88,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (406,'Veradis Ohlsen','France',54,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (407,'Austine Lockett','Sweden',47,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (408,'Ingeborg Perigoe','Indonesia',83,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (409,'Eduino Jerdan','China',100,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (410,'Frazer Bierling','Colombia',8,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (411,'Bonni Simoneschi','Pakistan',46,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (412,'Frankie Corstorphine','Cameroon',33,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (413,'Zane Handrock','Indonesia',33,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (414,'Marga Sloegrave','Indonesia',20,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (415,'Tammy Rubinchik','Poland',84,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (416,'Renaud Pershouse','Philippines',54,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (417,'Adamo Loft','Malaysia',24,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (418,'Veronike Tiery','Albania',78,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (419,'Sander Dyton','France',2,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (420,'Bria Leatham','Mexico',63,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (421,'Skipp Puckring','Indonesia',14,4,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (422,'Minette Yesinin','Philippines',91,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (423,'Lukas O''Connel','United States',62,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (424,'Lianna O''Crigan','Burkina Faso',23,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (425,'Barron Sprason','China',24,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (426,'Roch Guild','Brazil',17,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (427,'Raf Megany','Russia',0,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (428,'Joshuah Browncey','Ireland',27,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (429,'Ernesto Fackrell','Brazil',55,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (430,'Russ Melmoth','Serbia',54,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (431,'Natale Spilisy','Philippines',2,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (432,'Elinore Weymouth','China',14,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (433,'Gerard Compfort','China',24,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (434,'Derward Scarrott','Philippines',86,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (435,'Eyde Dubarry','Finland',94,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (436,'Ody Gill','Czech Republic',35,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (437,'Karrie Woodham','Jordan',67,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (438,'Brion Lochead','Indonesia',42,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (439,'Ricca Dailly','China',53,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (440,'Mollie Harms','Finland',97,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (441,'Etta Dunster','Cyprus',83,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (442,'Nora Vail','China',69,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (443,'Genni Eccleston','China',77,1,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (444,'Em Mattiassi','Egypt',80,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (445,'Carolan Leare','China',95,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (446,'Deborah Saffell','Indonesia',63,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (447,'Kelcey Tollady','Philippines',7,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (448,'Katina Chatfield','Brazil',91,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (449,'Pauli Ruben','China',12,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (450,'Krystyna Gooday','Mexico',82,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (451,'Natalya Carslake','Poland',23,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (452,'Florette Cavan','Peru',0,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (453,'Eadie O''Donnell','Azerbaijan',58,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (454,'Trueman Brimmell','Indonesia',8,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (455,'Marcelo Hanvey','Chile',9,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (456,'Willard Eldred','Niger',33,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (457,'Clio Koeppe','Philippines',23,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (458,'Egan Shephard','Poland',99,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (459,'Mufinella Esh','Philippines',97,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (460,'Bev Espasa','Russia',80,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (461,'Vivienne Mainz','Japan',85,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (462,'Cornie Mohan','Peru',7,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (463,'Lyndy Dumingo','Jamaica',88,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (464,'Farrell Waldera','Malaysia',13,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (465,'Lloyd Garlee','Argentina',39,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (466,'Godfree Ranfield','China',95,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (467,'Hale Littlewood','China',9,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (468,'Bernardo Errichelli','Russia',38,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (469,'Dorelia Chasemoore','Chile',14,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (470,'Jackquelin Barfitt','Thailand',95,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (471,'Shermie Stout','Japan',70,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (472,'Ardella Yashaev','Sweden',90,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (473,'Frannie Jearum','Armenia',53,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (474,'Bradney Barck','Japan',70,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (475,'Wyatan Kislingbury','China',55,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (476,'Hector Grimditch','Vietnam',34,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (477,'Lemmie Willoughley','Pakistan',69,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (478,'Jefferson Couth','China',22,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (479,'Niel Aynscombe','Czech Republic',38,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (480,'Gardener Scotland','Syria',46,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (481,'Gustavo Ruffey','Russia',16,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (482,'Alvie Bonsale','Indonesia',31,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (483,'Inna Crowche','Lithuania',12,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (484,'Barbette Crosse','Indonesia',0,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (485,'Carl Mathiot','China',31,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (486,'Tallulah Karim','Guatemala',30,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (487,'Nanine Wickey','China',18,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (488,'Courtney Giorgini','China',32,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (489,'Coral Ary','Portugal',76,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (490,'Kelley Berthe','Indonesia',66,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (491,'Collie Hebblewhite','China',83,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (492,'Eleni Shailer','Russia',38,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (493,'Othello Gately','Venezuela',58,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (494,'Cordi Feben','Czech Republic',49,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (495,'Caresse Marns','Colombia',18,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (496,'Kati Hove','France',8,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (497,'Zabrina Greig','Mongolia',69,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (498,'Dennis Pally','Portugal',96,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (499,'Abbey Parnby','China',76,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (500,'Kipp Beaves','Iran',52,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (501,'Marven Turfus','Serbia',100,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (502,'Tally Heathwood','Indonesia',46,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (503,'Christoforo Lovick','Indonesia',65,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (504,'Brina Sheryne','Nigeria',23,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (505,'Miguelita Yokel','China',31,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (506,'Donall Tuberfield','Botswana',7,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (507,'Fulton Cleugher','China',57,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (508,'Carly Scates','Kenya',59,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (509,'Berry Rochford','Burkina Faso',56,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (510,'Halli Aggas','Poland',48,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (511,'Linnie Benazet','Cambodia',85,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (512,'Kary Woodroff','Brazil',22,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (513,'Allene Sowter','China',44,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (514,'Northrup Dymond','Netherlands',32,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (515,'Avram Spriddle','China',98,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (516,'Adelind Blackboro','China',51,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (517,'Nissy Senechault','Poland',41,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (518,'Eb Yeeles','Poland',37,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (519,'Robenia Risbie','Indonesia',94,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (520,'Lonni Spenton','China',98,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (521,'Kristopher Aulds','Bosnia and Herzegovina',17,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (522,'Gilli Nuttall','Malaysia',66,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (523,'Gretchen Minihane','Tajikistan',56,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (524,'Terrill Casperri','Philippines',10,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (525,'Jereme Gaunt','China',82,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (526,'Anetta Mityakov','Philippines',84,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (527,'Terra Hurrion','Indonesia',69,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (528,'Rosabelle Graser','Ukraine',60,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (529,'Ritchie Herety','Sweden',100,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (530,'Jasen Bolderson','Jordan',42,5,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (531,'Duff Skarman','Burkina Faso',9,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (532,'Consalve Denham','Thailand',46,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (533,'Kimmie Buckenhill','Indonesia',87,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (534,'Verena Dinsey','Mexico',31,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (535,'Dougie Innis','Democratic Republic of the Congo',85,6,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (536,'Bernette Keers','Kenya',95,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (537,'Constantia Westwater','Ireland',55,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (538,'Prentice Barense','China',95,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (539,'Elicia Stilldale','Japan',76,3,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (540,'Cesar Evangelinos','China',86,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (541,'Donall Calender','Indonesia',36,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (542,'Maryanna Bouzek','China',88,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (543,'Alessandro Fowlie','Bangladesh',61,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (544,'Oberon Kyne','Guatemala',36,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (545,'Vonnie Strand','Indonesia',19,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (546,'Stephannie Yushmanov','Denmark',83,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (547,'Rustin Lavallin','Tanzania',51,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (548,'Masha Wherrett','Bolivia',67,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (549,'Aldridge Sword','Ireland',30,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (550,'Othilia Watterson','France',67,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (551,'Dosi Shieber','Portugal',23,5,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (552,'Clark Greeve','Mexico',0,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (553,'Vinita Poulett','France',50,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (554,'Mic Rabl','Indonesia',64,4,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (555,'Kerwin Knewstub','Malaysia',41,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (556,'Jobyna Filer','Madagascar',54,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (557,'Ophelia Feehan','Indonesia',68,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (558,'Brina Pomery','Kazakhstan',77,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (559,'Hobart Dudleston','Russia',17,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (560,'Gardy Lepick','Indonesia',96,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (561,'Wilburt Samson','Tanzania',45,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (562,'Darleen Oscroft','Japan',94,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (563,'Jacki Chaffer','Russia',71,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (564,'Guss Boutellier','Ivory Coast',24,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (565,'Teri Abrahamian','Indonesia',52,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (566,'Morgun Taggert','Vietnam',32,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (567,'Alisa Warder','Russia',69,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (568,'Salomon Strain','Brazil',41,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (569,'Lew Mitcham','Sweden',8,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (570,'Shannah Keemer','Philippines',8,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (571,'Kevan Beushaw','Sri Lanka',74,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (572,'Terrill Garrish','Mexico',37,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (573,'Audra Gillbee','Finland',14,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (574,'Hunter Bilt','Botswana',37,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (575,'Raviv Tann','China',92,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (576,'Ernestine Eggle','China',54,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (577,'Cornelia Wheatman','China',33,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (578,'Free Gove','Mauritania',64,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (579,'Dore Espine','Indonesia',20,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (580,'Susanne Dizlie','Finland',5,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (581,'Skipp Gleave','Indonesia',44,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (582,'Selig Sawrey','Czech Republic',23,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (583,'Nana Keems','China',20,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (584,'Jay Element','Kosovo',26,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (585,'Twyla Slafford','Greece',60,2,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (586,'Julietta Astin','Mexico',75,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (587,'Gayler Beckitt','Ukraine',15,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (588,'Ferne Gandar','Portugal',60,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (589,'Coralie Jankowski','China',8,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (590,'Tobin Ludlom','Indonesia',7,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (591,'Sada Chrstine','France',10,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (592,'Leia Di Bartolomeo','Indonesia',32,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (593,'Franklin Cobbe','Ukraine',79,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (594,'Valentia Peyto','China',25,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (595,'Rowena Buske','Thailand',83,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (596,'Mellie De Pero','Indonesia',93,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (597,'Cybil Seide','Indonesia',89,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (598,'Dar Pridie','Nicaragua',79,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (599,'Wendie Fotheringham','United States',40,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (600,'Marget Backson','Palestinian Territory',53,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (601,'Carlye Meharg','Mexico',54,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (602,'Renee Lymer','France',81,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (603,'Darbee Gallo','Philippines',67,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (604,'Israel Seeking','South Africa',48,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (605,'Traci Ransom','Portugal',88,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (606,'Tiffanie Baldinotti','Dominican Republic',88,7,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (607,'Shell Ingall','Egypt',100,3,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (608,'Eadmund Mager','China',95,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (609,'Janela Milburne','United States',23,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (610,'Abigail Fowlestone','Indonesia',14,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (611,'Cortney Absalom','Israel',89,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (612,'Olympe Hedde','South Korea',75,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (613,'Courtney Polendine','Ukraine',38,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (614,'Gayel Meggison','Ukraine',18,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (615,'Eberto Pettingill','Canada',15,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (616,'Nolan Bowers','Poland',36,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (617,'Wanids Livens','Thailand',28,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (618,'Paige Smeeton','Brazil',64,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (619,'Kaila Dyton','Mauritius',78,8,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (620,'Sascha Thunderchief','Mexico',53,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (621,'Sylvan Boughey','Russia',22,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (622,'Esther Maier','Indonesia',28,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (623,'Grethel Riddell','Brazil',80,8,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (624,'Godard Gannan','Kazakhstan',24,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (625,'Izabel Wager','China',95,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (626,'Nani Davidov','Russia',28,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (627,'Kirbee Lightning','Colombia',31,6,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (628,'Trevar Golde','Indonesia',85,3,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (629,'Hannah Heinle','Czech Republic',1,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (630,'Whitby Innman','United Kingdom',51,6,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (631,'Bertram Freezer','China',100,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (632,'Ree Vickar','Iran',0,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (633,'Matthieu Glandon','Brazil',65,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (634,'Fletch Kitcher','Cuba',12,5,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (635,'Iormina Izat','Indonesia',48,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (636,'Nessa Bernadon','Yemen',87,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (637,'Stevy Massen','Netherlands',79,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (638,'Birch Brockington','Niger',74,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (639,'Brigid Beningfield','Portugal',78,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (640,'Elissa Woffinden','Madagascar',24,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (641,'Keir Chaloner','China',64,3,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (642,'Zonda MacKintosh','Portugal',55,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (643,'Clay Saye','China',46,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (644,'Kristina McKeady','China',72,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (645,'Agnese Mintoff','Ghana',18,7,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (646,'Bobbi Leversha','Brazil',21,7,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (647,'Avery Cambden','Afghanistan',72,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (648,'Delphinia Walding','Russia',29,8,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (649,'Dyanna Slaney','China',26,5,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (650,'Calida Easey','Colombia',28,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (651,'Gabriel Cella','Portugal',55,1,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (652,'Anderea Bole','Tunisia',4,2,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (653,'Farrell Guerrier','Russia',95,2,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (654,'Hall Thunderman','Honduras',97,4,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (655,'Vergil Knappett','Kiribati',71,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (656,'Davey Rannells','Russia',64,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (657,'Eirena Lambis','China',17,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (658,'Elwood Niset','South Korea',73,7,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (659,'Tobe Boyland','Syria',24,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (660,'Abelard Buterton','Philippines',52,3,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (661,'Nataline Jessen','Greece',2,4,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (662,'Chloette MacRonald','Russia',6,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (663,'Sanders Buxy','Indonesia',87,1,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (664,'Zena Kinkaid','Madagascar',54,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (665,'Bernie McLurg','China',20,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (666,'Archer Greening','Indonesia',49,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (667,'Giselle Lared','China',61,5,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (668,'Bert Headrick','Hungary',98,5,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (669,'Erminie Ballach','France',4,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (670,'Artus Ferrari','United States',67,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (671,'Karlik Forster','China',29,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (672,'Sigismond Henric','Papua New Guinea',24,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (673,'Tonye Potkin','Indonesia',28,6,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (674,'Felipe Grassot','Japan',47,4,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (675,'Jerry McCague','Thailand',93,1,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (676,'Sarita Cathesyed','China',44,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (677,'Amandie Clavering','Philippines',84,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (678,'Bernhard Lilie','Indonesia',77,4,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (679,'Myer Christiensen','China',99,3,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (680,'Chas Lilie','Brazil',58,2,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (681,'Katinka Bareford','United States',14,3,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (682,'Francisca Tredger','Mauritius',93,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (683,'Sada Silverson','Thailand',81,6,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (684,'Prue Absolom','Sweden',85,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (685,'Kiersten Commusso','China',36,2,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (686,'Matthieu Dovington','China',15,7,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (687,'Sasha Kneeshaw','Russia',29,5,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (688,'Merrill Solley','Brazil',68,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (689,'Spence Kinsley','Poland',41,1,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (690,'Fonzie Hammersley','Indonesia',66,6,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (691,'Glennis Quernel','China',79,6,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (692,'Ronnie Mogg','Denmark',21,6,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (693,'Lock Bilbrey','Bolivia',72,4,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (694,'Ian Moss','Sierra Leone',77,7,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (695,'Eddie Bofield','Poland',62,4,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (696,'Verge Yewdale','Portugal',59,8,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (697,'Lorenza Creasey','North Korea',91,8,5);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (698,'Keefer Pasticznyk','Japan',31,8,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (699,'Brittney Ripper','Russia',31,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (700,'Rheba Van De Cappelle','China',74,3,7);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (701,'Fabe O'' Quirk','China',53,2,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (702,'Jaymee Ralfe','Kyrgyzstan',76,7,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (703,'Brigid de Keep','United States',4,6,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (704,'Nevin Marczyk','Philippines',73,2,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (705,'Mariel Baty','China',49,5,4);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (706,'Alfred Breem','Indonesia',26,1,2);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (707,'Jany Knewstubb','Indonesia',40,8,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (708,'Carine Killgus','Bangladesh',76,1,1);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (709,'Kimmi Feeny','Indonesia',63,8,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (710,'Nevsa Jerrams','Lithuania',22,7,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (711,'Wilden Swindle','Cuba',56,2,6);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (712,'Lee Schimonek','Nigeria',94,6,3);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (713,'Gunilla Crosbie','Turkey',27,1,8);
INSERT INTO mep(mepID,name,countryOfOrigin,loyaltyScore,partyID,recommendedPartyID) VALUES (714,'Forester Nusche','Macedonia',42,1,4);


